---
version: 2

project_name: homer-service-discovery

release:
  github:
    owner: Pro-Tweaker
    name: homer-service-discovery

builds:
  - main: ./cmd/main.go
    binary: main
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "7"

dockers_v2:
  - images:
      - "ghcr.io/Pro-Tweaker/{{ .ProjectName }}"
    tags:
      - "{{ .Tag }}"
      - "latest"
      - "v{{ .Major }}"
      - "v{{ .Major }}.{{ .Minor }}"
    dockerfile: Dockerfile.goreleaser
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/arm/v7

archives:
  - name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{- title .Os }}_{{- if eq .Arch "amd64" }}x86_64{{- else if eq .Arch "386" }}i386{{- else }}{{ .Arch }}{{ end }}

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

signs:
  - artifacts: checksum
    args: ["--batch", "-u", "{{ .Env.GPG_FINGERPRINT }}", "--output", "${signature}", "--detach-sign", "${artifact}"]
